<?php
/**
 * @copyright	Copyright (C) 2005 - 2010 Joomlashack / Joomlapraise / Meritage Assets
 * @author		Jeremy Wilken - Joomlashack
 * @package		Wright
 *
 * Do not edit this file directly. You can copy it and create a new file called
 * 'custom.php' in the same folder, and it will override this file. That way
 * if you update the template ever, your changes will not be lost.
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
?>
<doctype>
<html>
<head>


<?php //echo "<pre>";print_r($this);exit;?>
<script type="text/javascript" src="<?php echo $this->baseurl ?>/templates/<?php echo $this->document->template;?>/js/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseurl ?>/templates/<?php echo $this->document->template;?>/js/superfish.js"></script>
<script type="text/javascript" src="<?php echo $this->baseurl ?>/templates/<?php echo $this->document->template;?>/js/jquery.innerfade.js"></script>
<script type="text/javascript">
	jQuery('document').ready(function($){
	// superfish
	jQuery('#nav ul.menu')
	.find('li.current_page_item,li.current_page_parent,li.current_page_ancestor,li.current-cat,li.current-cat-parent')
	  .addClass('current')
	  .end()
	  .superfish({
	});
	// rounded images

	// fading testimonials
	jQuery('.testimonials').innerfade({
	animationtype: 'fade',
	speed: 'normal',
	timeout: 4000,
	type: 'sequence',
	containerheight: '3.5em'});
});
</script>

<w:head />
<link href="<?php echo $this->baseurl;?>/templates/<?php echo $this->document->template;?>/css/superfish.css" rel="stylesheet" type="text/css" media="screen" />
<link href="<?php echo $this->baseurl;?>/templates/<?php echo $this->document->template;?>/css/template.css" rel="stylesheet" type="text/css" media="screen" />
<!--[if IE 6]>
<link href="<?php echo $this->baseurl;?>/templates/<?php echo $this->template;?>/css/ie.css" rel="stylesheet" type="text/css" media="screen" />
<![endif]-->
<!--[if IE 7]>
<link href="<?php echo $this->baseurl;?>/templates/<?php echo $this->template;?>/css/ie7.css" rel="stylesheet" type="text/css" media="screen" />
<![endif]-->
<!--[if IE 8]>
<link href="<?php echo $this->baseurl;?>/templates/<?php echo $this->template;?>/css/ie8.css" rel="stylesheet" type="text/css" media="screen" />
<![endif]-->
</head>
<body <?php if ($this->countModules( 'bodyclass' )) : ?> class="<jdoc:include type="modules" name="bodyclass" style="raw" />"<?php endif; ?>>
<div id="pagewrap">
       <div id="header" class="image">
			<div class="innerwrap">
				<?php if ($this->countModules( 'top' )) : ?>
					<div id="topnav">
                            <w:nav name="top" chrome="none" />
					</div>
				<?php endif; ?>
                      <w:logo chrome="none"/>
			</div><!--innerwrap-->
         </div>
          <?php if($this->countModules('menu')) : ?>
          <div id="nav">
            <div class="innerwrap">
                <div id="menu">
                    <w:module type="single" name="menu" chrome="none" />
                </div>
            </div>
          </div>
          <?php endif; ?>
    <div id="wrap">
	<?php if($this->countModules('grid-top')) : ?>
		<div id="container" class="container_12">
			<div id="leader">
				<div id="grid-top">
				  <w:module type="grid" name="grid-top" chrome="wrightflexgrid" />
				  <div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div><!--/#leader-->
        </div>
	<?php endif; ?>
			<div id="container" class="container_12">
                <div class="mid_w_wide">
					<div id="content">
						<section>
							<?php if ($this->countModules( 'breadcrumbs' )) : ?>
							<div id="breadcrumbs">
								<w:module name="breadcrumbs" type="single" />
							</div>
							 <?php endif; ?>
							<w:content />
						</section>
					</div>
					<aside id="sidebar1">
						<div class="sidebar">
							<w:module name="sidebar1" chrome="xhtml" />
						</div>
					</aside>
					<aside id="sidebar2">
						<div class="sidebar">
							<w:module name="sidebar2" chrome="xhtml" />
						</div>
					</aside>
                  </div>
                  <div class="clear"></div>
			</div>
        </div>

</div>
			<div id="footer">
				<div class="container_12">		  		 
						  <div id="grid-bottom">
								<w:module type="grid" name="grid-bottom" chrome="wrightflexgrid" />
						   <div class="clear"></div>
						 </div>
						<div class="clear"></div>
						<div id="bottom"> <w:module type="single" name="footer" chrome="none" />  </div>
						<div class="copy">
							<w:footer />
						</div>
				</div><!-- /container_24 -->
                <div class="clear"></div>
		  	</div><!-- /#footer -->
</body>
</html>
