<?php
/**
 * @copyright	Copyright (C) 2005 - 2010 Joomlashack / Joomlapraise / Meritage Assets
 * @author		Jeremy Wilken - Joomlashack
 * @package		Wright
 *
 * Do not edit this file directly. You can copy it and create a new file called
 * 'custom.php' in the same folder, and it will override this file. That way
 * if you update the template ever, your changes will not be lost.
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
?>
<doctype>
<html>
<head>


<?php //echo "<pre>";print_r($this);exit;?>
<script type="text/javascript" src="<?php echo $this->baseurl ?>/templates/<?php echo $this->document->template;?>/js/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseurl ?>/templates/<?php echo $this->document->template;?>/js/superfish.js"></script>
<script type="text/javascript" src="<?php echo $this->baseurl ?>/templates/<?php echo $this->document->template;?>/js/jquery.innerfade.js"></script>
<script type="text/javascript">
	jQuery('document').ready(function($){
	// superfish
	jQuery('#nav ul.menu')
	.find('li.current_page_item,li.current_page_parent,li.current_page_ancestor,li.current-cat,li.current-cat-parent')
	  .addClass('current')
	  .end()
	  .superfish({
	});
	// rounded images

	// fading testimonials
	jQuery('.testimonials').innerfade({
	animationtype: 'fade',
	speed: 'normal',
	timeout: 4000,
	type: 'sequence',
	containerheight: '3.5em'});
});
</script>
<link href="<?php echo $this->baseurl;?>/templates/<?php echo $this->document->template;?>/css/superfish.css" rel="stylesheet" type="text/css" media="screen" />
<link href="<?php echo $this->baseurl;?>/templates/<?php echo $this->document->template;?>/css/template.css" rel="stylesheet" type="text/css" media="screen" />
<w:head />

<!--[if IE 6]>
<link href="<?php echo $this->baseurl;?>/templates/<?php echo $this->template;?>/css/ie.css" rel="stylesheet" type="text/css" media="screen" />
<![endif]-->
<!--[if IE 7]>
<link href="<?php echo $this->baseurl;?>/templates/<?php echo $this->template;?>/css/ie7.css" rel="stylesheet" type="text/css" media="screen" />
<![endif]-->
<!--[if IE 8]>
<link href="<?php echo $this->baseurl;?>/templates/<?php echo $this->template;?>/css/ie8.css" rel="stylesheet" type="text/css" media="screen" />
<![endif]-->

</head>

<body <?php if ($this->countModules( 'bodyclass' )) : ?> class="<jdoc:include type="modules" name="bodyclass" style="raw" />"<?php endif; ?>>

<div id="pagewrap">
       <div id="header" class="image">
			<div class="innerwrap">
				<?php if ($this->countModules( 'topmenu' )) : ?>
					<div id="topnav">
                            <w:nav name="topmenu" chrome="none" />
					</div>

				<?php endif; ?>
                      <w:logo chrome="none"/>
			</div><!--innerwrap-->



         </div>
          <?php if($this->countModules('menu')) : ?>
          <div id="nav">
            <div class="innerwrap">
                <div id="menu">
                    <w:module type="single" name="menu" chrome="none" />
                </div>
            </div>
          </div>
          <?php endif; ?>
    <div id="wrap">

    	<?php if($this->countModules('Leader1') or $this->countModules('Leader2') or $this->countModules('Leader3')) : ?>

 <div id="container" class="container_24">

		<div id="leader">
		 	  <?php if ($this->countModules( 'Leader1' )) : ?>
                    <div class="grid_8">
		 	       <w:module name="Leader1"  />
                    </div>
		 	  <?php endif; ?>
		 	  <?php if ($this->countModules( 'Leader2' )) : ?>
                    <div class="grid_8">
		 	      <w:module name="Leader2"  />
                      </div>
		 	  <?php endif; ?>
		 	  <?php if ($this->countModules( 'Leader3' )) : ?>
                <div class="grid_8">
		 	     <w:module name="Leader3"  />

		 	  <?php endif; ?>
		 	  <div class="clear"></div>
		        </div><!--/#leader-->


             </div>
    </div>
        <?php endif; ?>
        <div id="container" class="container_12">


                <div id="content">

        	        <section>
                        <?php if ($this->countModules( 'breadcrumbs' )) : ?>
                        <div id="breadcrumbs">
                            <w:module name="breadcrumbs" type="single" />
                        </div>
                         <?php endif; ?>
						<w:content />
					</section>
            </div>

                    <div class="sidebar">
					<aside id="sidebar1">
						<w:module name="sidebar1" chrome="xhtml" />
					</aside>
                    </div>
                    <div class="sidebar">
					<aside id="sidebar2">
						<w:module name="sidebar2" chrome="xhtml" />
					</aside>
                    </div>



             </div>

        </div>
</div>

<div id="footer">
				<div class="container_24">
		  		  <?php if ($this->countModules( 'Footer1' )) : ?>
						<div class="grid_8">
          		  		     <div class="inside">
          		  		        <w:module name="footer1" chrome="xhtml" />
          		  		      </div>
		  		        </div>
		  		   <?php endif; ?>

		  		   <?php if ($this->countModules( 'Footer2' )) : ?>
							<div class="grid_8">
								<div class="inside">
									 <w:module name="footer2" chrome="xhtml" />
								</div>
		  		            </div>
		  		   <?php endif; ?>

		  		   <?php if ($this->countModules( 'Footer3' )) : ?>
							<div class="grid_8">
								<div class="inside">
								    <w:module name="footer3" chrome="xhtml" />
								</div>
							</div>
		  		   <?php endif; ?>




         <div id="bottom"> <w:module type="single" name="copyright" chrome="none" />  </div>
            <div class="copy">
                              <w:footer />
                      </div>

				</div><!-- /container_24 -->
                <div class="clear"></div>

		  	</div><!-- /#footer -->



</body>
</html>
